// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGgnjF1aKNeJnzRBiO8qQmHyp69sWyts4',
    appId: '1:678430835771:web:5a071a280a265e8915481e',
    messagingSenderId: '678430835771',
    projectId: 'sizzleshare-ad1e0',
    authDomain: 'sizzleshare-ad1e0.firebaseapp.com',
    storageBucket: 'sizzleshare-ad1e0.firebasestorage.app',
    measurementId: 'G-DRJRVGE5CE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeZNMESicXncxUS8b_EcL38PLjY2xCWz8',
    appId: '1:678430835771:android:489fdbd24fc532f015481e',
    messagingSenderId: '678430835771',
    projectId: 'sizzleshare-ad1e0',
    storageBucket: 'sizzleshare-ad1e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUkhFcDIknHeDwq7xzrsMuIYN0Kq0jUhE',
    appId: '1:678430835771:ios:8c57f4cb489a5a6515481e',
    messagingSenderId: '678430835771',
    projectId: 'sizzleshare-ad1e0',
    storageBucket: 'sizzleshare-ad1e0.firebasestorage.app',
    iosBundleId: 'com.example.sizzleShare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUkhFcDIknHeDwq7xzrsMuIYN0Kq0jUhE',
    appId: '1:678430835771:ios:8c57f4cb489a5a6515481e',
    messagingSenderId: '678430835771',
    projectId: 'sizzleshare-ad1e0',
    storageBucket: 'sizzleshare-ad1e0.firebasestorage.app',
    iosBundleId: 'com.example.sizzleShare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGgnjF1aKNeJnzRBiO8qQmHyp69sWyts4',
    appId: '1:678430835771:web:79486d19ffb523cd15481e',
    messagingSenderId: '678430835771',
    projectId: 'sizzleshare-ad1e0',
    authDomain: 'sizzleshare-ad1e0.firebaseapp.com',
    storageBucket: 'sizzleshare-ad1e0.firebasestorage.app',
    measurementId: 'G-82697WDYB9',
  );
}
